#! /usr/bin/env bash
dot -Tpng arraylist.dot > arraylist.png
dot -Tpng avltree.dot > avltree.png
dot -Tpng binaryheap.dot > binaryheap.png
dot -Tpng btree.dot > btree.png
dot -Tpng doubleyLinkedList.dot > doublyLinkedList.png
dot -Tpng hashmap.dot > hashmap.png
dot -Tpng linked_list.dot > linked_list.png
dot -Tpng queue.dot > queue.png
dot -Tpng redblacktree.dot > redblacktree.png
dot -Tpng sets.dot > sets.png
dot -Tpng stack.dot > stack.png
